name: Mirror Docker Images to GHCR

on:
  workflow_dispatch:

jobs:
  mirror-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: alpine
            tag: "3.19"
          - image: alpine
            tag: "3.21"
          - image: alpine
            tag: "3.22"
          - image: nginx
            tag: "1.27"
          - image: nginx
            tag: "1.28"
          - image: nginx
            tag: "1.29"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ matrix.image }}:${{ matrix.tag }}

      - name: Tag image for GHCR
        run: |
          lower_owner="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          docker tag ${{ matrix.image }}:${{ matrix.tag }} ghcr.io/$lower_owner/${{ matrix.image }}:${{ matrix.tag }}

      - name: Push image to GHCR
        run: |
          lower_owner="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          docker push ghcr.io/$lower_owner/${{ matrix.image }}:${{ matrix.tag }}
